name: dio_http_cache_example
description: A demo of the dio_http_cache package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio_http_cache:
    path: ../
  dio: ^5.0.3

dev_dependencies:
  flutter_lints: ^2.0.1
#  flutter_test:
#    sdk: flutter

flutter:
  uses-material-design: true
